backend:
  branch: content
  name: git-gateway
collections:
  - name: "article"
    label: "Articles"
    label_singular: "Article"
    folder: "content/articles"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DDTHH:mm:ssZ", date_format: "dddd D MMMM YYYY,", time_format: "H:mm:ss" }
      - label: "Body"
        name: "body"
        widget: "markdown"
        editor_components: ["image", "read-more"]
        buttons: ["bold", "italic", "link", "heading-one", "heading-two", "heading-three", "heading-four", "heading-five", "heading-six", "quote", "bulleted-list", "numbered-list"]
  - name: "page"
    label: "Pages"
    label_singular: "Page"
    folder: "content/pages"
    create: true
    slug: "{{link}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Link", name: "link", widget: "string"}
      - label: "Body"
        name: "body"
        widget: "markdown"
        editor_components: ["image", "read-more"]
        buttons: ["bold", "italic", "link", "heading-one", "heading-two", "heading-three", "heading-four", "heading-five", "heading-six", "quote", "bulleted-list", "numbered-list"]
      - {label: "Menu label", name: "label", widget: "string", required: false}
      - {label: "Menu weight", name: "weight", widget: "number", required: false}
      - {label: "Show in top menu", name: "showInTopMenu", widget: "boolean"}
      - {label: "Show in left menu", name: "showInLeftMenu", widget: "boolean"}
      - {label: "Show in right menu", name: "showInRightMenu", widget: "boolean"}
  - name: "practitioner"
    label: "Practitioners"
    label_singular: "Practitioner"
    folder: "content/practitioners"
    create: true
    slug: "{{name}}"
    fields:
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Company", name: "company", widget: "string"}
      - {label: "Company website", name: "companyLink", widget: "string"}
      - {label: "Company logo", name: "companyLogo", widget: "image", allow_multiple: false}
      - label: "Activities"
        label_singular: "Activity"
        name: "activities"
        widget: "list"
        summary: "{{fields.activity}}"
        field: {label: "Activity", name: "activity", widget: "string"}
        minimize_collapsed: true
      - label: "Body"
        name: "body"
        widget: "markdown"
        editor_components: ["image"]
        buttons: ["bold", "italic", "link", "heading-one", "heading-two", "heading-three", "heading-four", "heading-five", "heading-six", "quote", "bulleted-list", "numbered-list"]
      - {label: "Menu weight", name: "weight", widget: "number", required: false}
      - {label: "Show in menu", name: "showInMenu", widget: "boolean", default: true}
media_folder: "public/uploads"
public_folder: "/uploads"
site_url: https://piith.nl
