backend:
  branch: content
  name: git-gateway
collections:
  - name: "page"
    label: "Pages"
    label_singular: "Page"
    folder: "content/pages"
    create: true
    slug: "{{link}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Link", name: "link", widget: "string"}
      - label: "Body"
        name: "body"
        widget: "markdown"
        editor_components: ["image", "read-more"]
        buttons: ["bold", "italic", "link", "heading-one", "heading-two", "heading-three", "heading-four", "heading-five", "heading-six", "quote", "bulleted-list", "numbered-list"]
      - {label: "Menu label", name: "label", widget: "string", required: false}
      - {label: "Menu weight", name: "weight", widget: "number", required: false}
      - {label: "Show in top menu", name: "showInTopMenu", widget: "boolean"}
      - {label: "Show in left menu", name: "showInLeftMenu", widget: "boolean"}
      - {label: "Show in right menu", name: "showInRightMenu", widget: "boolean"}
  - name: "article"
    label: "Articles"
    label_singular: "Article"
    folder: "content/articles"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DDTHH:mm:ssZ", date_format: "dddd D MMMM YYYY,", time_format: "H:mm:ss" }
      - label: "Body"
        name: "body"
        widget: "markdown"
        editor_components: ["image", "read-more"]
        buttons: ["bold", "italic", "link", "heading-one", "heading-two", "heading-three", "heading-four", "heading-five", "heading-six", "quote", "bulleted-list", "numbered-list"]
media_folder: "public/uploads"
public_folder: "/uploads"
site_url: https://piith.nl
