backend:
  branch: next
  name: git-gateway
collections:
  - name: "page" # Used in routes, e.g., /admin/collections/blog
    label: "Page" # Used in the UI
    folder: "content/pages" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{link}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Link", name: "link", widget: "string"}
      - label: "Body"
        name: "body"
        widget: "markdown"
        editor_components: ["image", "read-more"]
        buttons: ["bold", "italic", "link", "heading-one", "heading-two", "heading-three", "heading-four", "heading-five", "heading-six", "quote", "bulleted-list", "numbered-list"]
      - {label: "Menu label", name: "label", widget: "string", required: false}
      - {label: "Menu weight", name: "weight", widget: "number", required: false}
      - {label: "Show in top menu", name: "showInTopMenu", widget: "boolean"}
      - {label: "Show in left menu", name: "showInLeftMenu", widget: "boolean"}
      - {label: "Show in right menu", name: "showInRightMenu", widget: "boolean"}
  - name: "article" # Used in routes, e.g., /admin/collections/blog
    label: "Article" # Used in the UI
    folder: "content/articles" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}T{{hour}}:{{minute}}:{{second}}_{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime", date_format: "YYYY-MM-DD", time_format: "hh:mm:ss"}
      - label: "Body"
        name: "body"
        widget: "markdown"
        editor_components: ["image", "read-more"]
        buttons: ["bold", "italic", "link", "heading-one", "heading-two", "heading-three", "heading-four", "heading-five", "heading-six", "quote", "bulleted-list", "numbered-list"]
media_folder: "public/uploads"
public_folder: "/uploads"
